version: "3.9"

services:
  api.product:
    image: letranglan129/api-product:v0.1
    container_name: API.Product
    hostname: api-product-service
    build: 
        context: .
	network: host
        dockerfile: ./API.Product/Dockerfile
    ports:
      - "8000:8000"
    environment: 
        ASPNETCORE_HTTP_PORTS: "8000"
        PRODUCT_DB: "Server=ssh.letranglan.top;Database=MS_Product;User Id=sa;Password=785571Lan;TrustServerCertificate=True"
        RB_HOST: "rabbitmq-service"
        RB_USER: admin
        RB_PASS: admin
  
  api.cart:
    image: letranglan129/api-cart:v0.1
    container_name: API.Cart
    hostname: api-cart-service
    build: 
        context: .
	network: host
        dockerfile: ./API.Cart/Dockerfile
    ports:
      - "7000:7000"
    environment: 
        ASPNETCORE_HTTP_PORTS: "7000"
        CART_DB: "Server=ssh.letranglan.top;Database=MS_Cart;User Id=sa;Password=785571Lan;TrustServerCertificate=True"
        RB_HOST: "rabbitmq-service"
        RB_USER: admin
        RB_PASS: admin

  api.gateway:
    image: letranglan129/api-gateway:v0.1
    container_name: API.Gateway
    hostname: api-gateway-service
    build: 
        context: .
	network: host
        dockerfile: ./APIGateway/Dockerfile
    ports:
      - "8080:8080"
    links:
      - api.cart
      - api.product
    depends_on:
      - api.cart
      - api.product
    environment: 
        ASPNETCORE_HTTP_PORTS: "8080"

  webui:
    image: letranglan129/webui-client:v0.1
    container_name: webui.Client
    hostname: webui-client-service
    build: 
        context: .
	network: host
        dockerfile: ./WebUIClient/Dockerfile
    ports:
      - "9000:9000"
    links:
      - api.gateway
    environment: 
        ASPNETCORE_HTTP_PORTS: "9000"
        API_URL: "http://api-gateway-service:8080"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmqEB
    hostname: rabbitmq-service
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

 