apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-product
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-product
  template:
    metadata:
      labels:
        app: api-product
    spec:
      containers:
        - name: api-product
          image: letranglan129/api-product
          ports:
            - containerPort: 8000
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8000"
            - name: PRODUCT_DB
              value: "Server=ssh.letranglan.top;Database=MS_Product;User Id=sa;Password=785571Lan;TrustServerCertificate=True"
            - name: RB_HOST
              value: "rabbitmq-service"
            - name: RB_USER
              value: "admin"
            - name: RB_PASS
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: api-product-service
  namespace: my-namespace
spec:
  selector:
    app: api-product
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cart
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cart
  template:
    metadata:
      labels:
        app: api-cart
    spec:
      containers:
        - name: api-cart
          image: letranglan129/api-cart
          ports:
            - containerPort: 7000
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "7000"
            - name: CART_DB
              value: "Server=ssh.letranglan.top;Database=MS_Cart;User Id=sa;Password=785571Lan;TrustServerCertificate=True"
            - name: RB_HOST
              value: "rabbitmq-service"
            - name: RB_USER
              value: "admin"
            - name: RB_PASS
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: api-cart-service
  namespace: my-namespace
spec:
  selector:
    app: api-cart
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: letranglan129/api-gateway
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: my-namespace
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-client
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui-client
  template:
    metadata:
      labels:
        app: webui-client
    spec:
      containers:
        - name: webui-client
          image: letranglan129/webui-client
          ports:
            - containerPort: 9000
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "9000"
            - name: API_URL
              value: "http://api-gateway-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: webui-client-service
  namespace: my-namespace
spec:
  selector:
    app: webui-client
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: my-namespace
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
